pipeline:
  name: pskkiii
  identifier: pskkiii
  projectIdentifier: ab0000658
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fff
        identifier: fff
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sample_service_1689515979340
          environment:
            environmentRef: dev_1689515973396
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster_1689515973396
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
