pipeline:
  identifier: Build_Spotify_1698901590517
  name: Build Spotify
  orgIdentifier: default
  projectIdentifier: SMO
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698901436771
        repoName: Spotify
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - parallel:
                  - step:
                      type: Background
                      name: Background_1
                      identifier: Background_1
                      spec: {}
                  - step:
                      type: GitClone
                      name: spotify gitclone
                      identifier: spotify_gitclone
                      spec:
                        connectorRef: account.Github_OAuth_1698901436771
                        repoName: Spotify
                        cloneDirectory: https://github.com/nandireddy12321/Spotify.git
                        build:
                          type: branch
                          spec:
                            branch: master
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
